### ISSUE TITLE
subiquity/Install/install/postinstall/install_build-essentials returned non-zero exit status 100

### ISSUE THREAD

**Issue by basictheprogram** [boxcutter/ubuntu#202]
<img width="403" alt="Banners_and_Alerts_and_ubuntu2004_and_New_Issue_·_boxcutter_ubuntu" src="https://user-images.githubusercontent.com/6723257/120534631-af200c80-c3a7-11eb-95c4-62b7d83cabb8.png">

Not sure how to get to the local filesystem when the installer fails on a VMware Fusion build. The crash log is written to /var/crash/nnnnn.nnnnn.install_fail.crash

**Comment by basictheprogram** [comment]
This http/user-data got me around the above crash/error, I commented out the `build-essential` package
```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: vagrant
    password: '$6$iCc.WH.j$EuCSsvXtnIX2UnrunKZHApB3uvKuxplkAL1UBtBkab047y/jyn9WnpVAkc57jtqSv.hsLGje.milvneydC.Cw/'
    username: vagrant
  network:
    version: 2
    ethernets:
      enp0s3:
        dhcp4: true
        dhcp-identifier: mac
  ssh:
    install-server: true
  packages:
  #  - build-essential
    - perl
  late-commands:
    - 'echo "vagrant        ALL=(ALL)       NOPASSWD: ALL" > /target/etc/sudoers.d/vagrant'
    - chmod 440 /target/etc/sudoers.d/vagrant
    - apt-get -y install linux-headers-$(uname -r)
  locale: en_US
  keyboard:
    layout: us
    variant: ''
```
The problem now is Ethernet interface `ens32` does not get assigned an IP address.
